from main import db
from user.models import *

u1 = User(email="jbizzle@yale.edu", password="jason", firstname="Jason", lastname="Brooks")
u2 = User(email="kevin.abbott@yale.edu", password="kevin", firstname="Kevin", lastname="Abbott")
u3 = User(email="micah.rosales.iii@yale.edu", password="micah", firstname="Micah", lastname="Rosales")
db.session.add(u1)
db.session.add(u2)
db.session.add(u3)
db.session.commit()

p1=Party(name="Kevin's Birthday Bash", code="a5aafa", user=u1)
p2=Party(name="Jason's Party", code="JAS3", user=u2)
p3=Party(name="Pranav has wifi", code="A553", user=u3)
p4=Party(name="BASH", code="EHO", user=u2)
db.session.add(p1)
db.session.add(p2)
db.session.add(p3)
db.session.add(p4)
db.session.commit()

sl1=Song_List(party=p1)
sl2=Song_List(party=p2)
sl3=Song_List(party=p3)
sl4=Song_List(party=p4)
db.session.add(sl1)
db.session.add(sl2)
db.session.add(sl3)
db.session.add(sl4)
db.session.commit()

s1=Song(uid="supHTTP:L@$", votes=3, songlist=sl1)
s2=Song(uid="sasdfupHTTP:L@$", votes=4, songlist=sl1)
s3=Song(uid="s4u45pHTTP:L@$", votes=1, songlist=sl1)
s4=Song(uid="kldfjsupHTTP:L@$", votes=3, songlist=sl1)
s5=Song(uid="SDFSDFSDFupHTTP:L@$", votes=6, songlist=sl1)
db.session.add(s1)
db.session.add(s2)
db.session.add(s3)
db.session.add(s4)
db.session.add(s5)
db.session.commit()